import type { ToolTypeInfo } from "./extract";

export function toPascalCase(s: string): string {
  return s
    .replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^\w/, (c) => c.toUpperCase());
}

export function generateOutput(tools: ToolTypeInfo[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @zaikit/codegen-react — DO NOT EDIT",
    "",
    'import type { ReactNode } from "react";',
    'import type { ToolRenderProps, ToolRenderFn } from "@zaikit/react";',
    'import { useToolRenderer as _useToolRenderer } from "@zaikit/react";',
    "",
    "// ─── Types ───",
  ];

  for (const tool of tools) {
    const pascal = toPascalCase(tool.name);
    lines.push("");
    lines.push(`export type ${pascal}Input = ${tool.input};`);
    lines.push(`export type ${pascal}Output = ${tool.output};`);
    if (tool.suspend) {
      lines.push(`export type ${pascal}Suspend = ${tool.suspend};`);
    }
    if (tool.resume) {
      lines.push(`export type ${pascal}Resume = ${tool.resume};`);
    }
    if (tool.data) {
      lines.push(`export type ${pascal}Data = ${tool.data};`);
    }
  }

  lines.push("");
  lines.push("// ─── Typed Props ───");

  for (const tool of tools) {
    const pascal = toPascalCase(tool.name);
    const suspendType = tool.suspend ? `${pascal}Suspend` : "unknown";
    const resumeType = tool.resume ? `${pascal}Resume` : "unknown";
    const dataType = tool.data ? `${pascal}Data` : "Record<string, unknown>";
    lines.push("");
    lines.push(
      `export type ${pascal}ToolProps = ToolRenderProps<${pascal}Input, ${suspendType}, ${resumeType}, ${dataType}>;`,
    );
  }

  // ─── Tool Props Map + Typed useToolRenderer ───
  lines.push("");
  lines.push("// ─── Typed useToolRenderer ───");
  lines.push("");

  if (tools.length > 0) {
    lines.push("type ToolPropsMap = {");
    for (const tool of tools) {
      const pascal = toPascalCase(tool.name);
      lines.push(`  ${tool.name}: ${pascal}ToolProps;`);
    }
    lines.push("};");
    lines.push("");
    lines.push(
      "export function useToolRenderer<T extends keyof ToolPropsMap>(name: T, render: (props: ToolPropsMap[T]) => ReactNode): void;",
    );
    lines.push(
      "export function useToolRenderer(name: string, render: ToolRenderFn): void;",
    );
    lines.push(
      "export function useToolRenderer(name: string, render: ToolRenderFn): void {",
    );
    lines.push("  _useToolRenderer(name, render);");
    lines.push("}");
  } else {
    lines.push("export { _useToolRenderer as useToolRenderer };");
  }

  // ─── Tool Name Union ───
  lines.push("");
  lines.push("// ─── Tool Name Union ───");
  lines.push("");
  if (tools.length > 0) {
    const union = tools.map((t) => `  | "${t.name}"`).join("\n");
    lines.push(`export type ToolName =\n${union};`);
  } else {
    lines.push("export type ToolName = never;");
  }
  lines.push("");

  return lines.join("\n");
}
