// AUTO-GENERATED by @lioneltay/aikit-codegen-react — DO NOT EDIT

import type { ReactNode } from "react";
import type { ToolRenderProps, ToolRenderFn } from "@lioneltay/aikit-react";
import { useToolRenderer as _useToolRenderer } from "@lioneltay/aikit-react";

// ─── Types ───

export type GetWeatherInput = { location: string; };
export type GetWeatherOutput = { location: string; temperature: number; condition: string; humidity: number; windSpeed: number; };

export type DeleteRecordsInput = { table: string; count: number; };
export type DeleteRecordsOutput = { error: string; deleted?: undefined; reason?: undefined; remaining?: undefined; } | { deleted: number; reason: string; error?: undefined; remaining?: undefined; } | { deleted: number; remaining: number; error?: undefined; reason?: undefined; };
export type DeleteRecordsSuspend = { message: string; };
export type DeleteRecordsResume = { approved: boolean; };

export type BookFlightInput = { destination: string; date: string; };
export type BookFlightOutput = { error: string; confirmation?: undefined; status?: undefined; flight?: undefined; seat?: undefined; } | { confirmation: string; status: string; flight: { id: string; airline: string; price: number; departure: string; }; seat: "window" | "aisle" | "middle"; error?: undefined; };
export type BookFlightSuspend = { flights: { id: string; airline: string; price: number; departure: string; }[]; };
export type BookFlightResume = { selectedFlightId: string; seatPreference: "window" | "aisle" | "middle"; };

export type SendEmailInput = { to: string; subject: string; body: string; };
export type SendEmailOutput = { sent: boolean; reason: string; to?: undefined; subject?: undefined; body?: undefined; } | { sent: boolean; to: string; subject: string; body: string; reason?: undefined; };
export type SendEmailSuspend = { preview: { to: string; subject: string; body: string; }; };
export type SendEmailResume = { approved: boolean; to?: string | undefined; subject?: string | undefined; body?: string | undefined; };

// ─── Typed Props ───

export type GetWeatherToolProps = ToolRenderProps<GetWeatherInput>;

export type DeleteRecordsToolProps = ToolRenderProps<DeleteRecordsInput, DeleteRecordsSuspend, DeleteRecordsResume>;

export type BookFlightToolProps = ToolRenderProps<BookFlightInput, BookFlightSuspend, BookFlightResume>;

export type SendEmailToolProps = ToolRenderProps<SendEmailInput, SendEmailSuspend, SendEmailResume>;

// ─── Typed useToolRenderer ───

type ToolPropsMap = {
  get_weather: GetWeatherToolProps;
  delete_records: DeleteRecordsToolProps;
  book_flight: BookFlightToolProps;
  send_email: SendEmailToolProps;
};

export function useToolRenderer<T extends keyof ToolPropsMap>(name: T, render: (props: ToolPropsMap[T]) => ReactNode): void;
export function useToolRenderer(name: string, render: ToolRenderFn): void;
export function useToolRenderer(name: string, render: ToolRenderFn): void {
  _useToolRenderer(name, render);
}

// ─── Tool Name Union ───

export type ToolName =
  | "get_weather"
  | "delete_records"
  | "book_flight"
  | "send_email";
